### ISSUE TITLE
Support for sidekiq 4.1.0

### ISSUE THREAD

**Issue by holoiii** [anujdas/sidekiq-hierarchy#2]
First off, this is an amazing gem, and thank you for your contribution! Are there any plans to update this gem to work with sidekiq 4.1.0?

Or if there aren't any, could you possibly point me in the right direction for upgrading this myself?

**Comment by anujdas** [comment]
Thanks @holoiii! Glad to hear it. I looked into supporting Sidekiq 4.1.0 and it seems like it should be trivial; the tests already pass. I'm just doing a little legwork to ensure that I didn't break anything under Sidekiq 3.x and I'll push the change.

**Comment by holoiii** [comment]
@anujdas Thanks for the quick reply! Awesome news :)

**Comment by anujdas** [comment]
Ok, v2.1.0 should work with Sidekiq 4.x. I've only tried it briefly though (although all specs pass), since I'm still using it with 3.x, so let me know if there are any issues.
