### ISSUE TITLE
Error when display workflow infos on web interface

### ISSUE THREAD

**Issue by hashtegner** [anujdas/sidekiq-hierarchy#4]
Hey!

First, thanks a lot for your hard work in this Gem. Your work is really appreciated.

The problem is when I access the Hierarchy tab on web interface, I click on the workflow to inspect it but, the following error occurred:

```
016-07-18 21:41:25 - TypeError - can't convert nil into an exact number:
    /usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/core_ext/time/calculations.rb:226:in `-'
    /usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/core_ext/time/calculations.rb:226:in `minus_with_duration'
    /usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/core_ext/time/calculations.rb:237:in `minus_with_coercion'
    /usr/local/bundle/gems/sidekiq-hierarchy-2.1.0/web/views/_workflow_progress_bar.erb:14:in `block in singleton class'
    /usr/local/bundle/gems/sidekiq-hierarchy-2.1.0/web/views/_workflow_progress_bar.erb:-5:in `instance_eval'
    /usr/local/bundle/gems/sidekiq-hierarchy-2.1.0/web/views/_workflow_progress_bar.erb:-5:in `singleton class'
    /usr/local/bundle/gems/sidekiq-hierarchy-2.1.0/web/views/_workflow_progress_bar.erb:-7:in `__tilt_70165668977040'
```

I inspect the workflow and apparently, the `enqueued_at` info is nil, breaking the view.

![workflow](http://i.imgur.com/yKyrqzC.png)

I'm using  Sidekiq 4.1.1.

Can you help me or I can help you?

**Comment by anujdas** [comment]
That's interesting @alesshh. Thanks for the info; `enqueued_at` should never be nil for any job. Would I be correct in guessing that you just started using the gem, and that this is a job that was enqueued before you enabled `sidekiq-hierarchy`? That would definitely result in a job without the enqueued_at timestamp but with the rest of them.

What would you prefer to see here? The easiest answer is to start with no jobs enqueued when working with sidekiq-hierarchy for the first time, but I'm guessing this is no longer possible. If there's only one such workflow, you could manually remove it from the records via console; let me know if this is something you're interested in. The most generalised solution, maybe, is to patch `Job#enqueued_at` to return `run_at` if nil, but this seems very hack-ish to me.

Thoughts?

**Comment by hashtegner** [comment]
Hello @anujdas.

I tried enqueue after that I enabled sidekiq-hierarchy.

Given that I am only enqueuing the job, the result is this:

```
irb(main):001:0> CsvGenerator::BaseJob.perform_async
=> "96cbc10d520da1e9c08ec75d"

irb(main):013:0* job = Sidekiq::Hierarchy::Workflow.find_by_jid('96cbc10d520da1e9c08ec75d')
=> #<Sidekiq::Hierarchy::Workflow:0x007f154be96cd8 @root=#<Sidekiq::Hierarchy::Job:0x007f154be96d00 @jid="96cbc10d520da1e9c08ec75d">>

irb(main):014:0> job.status
=> :unknown

irb(main):015:0> job.enqueued_at
=> nil

```

I tried to patch `Job#enqueued_at` and a new error appeared:

```
2016-07-19 20:55:51 - TypeError - no implicit conversion of nil into String:
    /usr/local/bundle/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
    /usr/local/bundle/gems/json-1.8.3/lib/json/common.rb:155:in `new'
    /usr/local/bundle/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
    /usr/local/bundle/gems/sidekiq-4.1.1/lib/sidekiq.rb:176:in `load_json'
    /usr/local/bundle/gems/sidekiq-hierarchy-2.1.0/lib/sidekiq/hierarchy/job.rb:89:in `info'
    /usr/local/bundle/gems/sidekiq-hierarchy-2.1.0/web/views/_job_tree_node.erb:4:in `block in singleton class'
    /usr/local/bundle/gems/sidekiq-hierarchy-2.1.0/web/views/_job_tree_node.erb:-5:in `instance_eval'

```

**Comment by anujdas** [comment]
Interesting. I'm not sure how you patched things for the latter, but for the first part, I have two questions:
- Did you make sure to load in the sidekiq-hierarchy client middleware for both the server and the client? Can you verify by checking `Sidekiq.client_middleware`/`Sidekiq.server_middleware`?
- Are you by any chance using Sidekiq Pro with reliable-scheduler extensions? I have not tried it, but the release notes for Sidekiq Pro state that client-side middleware is not executed when the option is enabled. Given that you're not using scheduled jobs for your example, I doubt this would make a difference, though.

**Comment by hashtegner** [comment]
Hello @anujdas 
Problem solved!
I did added only at server_client config. 

Thanks a lot for all support and sorry about that.
